spring.application.name=cvm
server.port=8099
server.servlet.context-path=/cvm
monitor.log.path=./logs

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
server.tomcat.connection-timeout=600s


monitor.socket.host=127.0.0.1
monitor.socket.port=9527
# 取样间隔 ms
monitor.socket.time=500

# 总采样时间 ms
monitor.cpu.durationMs=10000
# 采样间隔 ms
monitor.cpu.intervalMs=500

# profiler
# 时长
monitor.sampleMillis=5000
# 间隔
monitor.cpu.sampleCount=50

monitor.heapdump.default.name=heapdump_

# h2\u6570\u636E\u5E93
spring.datasource.url=jdbc:h2:file:./db/monitor
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=cc
spring.datasource.password=123456

spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false


jcmd.path=${JAVA_HOME}\\bin\\jcmd.exe
# jcmd.path=/Library/Java/JavaVirtualMachines/jdk-11.jdk/Contents/Home/bin/jcmd

#jcmd8.path=/Library/Java/JavaVirtualMachines/jdk1.8.0_291.jdk/Contents/Home/bin/jcmd
#jcmd.path=D:\\visualvm_22\\jdk1.8.0_281\\bin\\jcmd.exe
jstack.path=D:\\visualvm_22\\jdk1.8.0_281\\bin\\jstack.exe
visualvm.path=D:\\visualvm_22\\jdk1.8.0_281\\bin\\jvisualvm.exe

command.encoding=UTF-8

# \u91C7\u6837\u95F4\u9694\uFF0C\u5355\u4F4D\u6BEB\u79D2
monitor.sample-interval-ms=5000
# \u6570\u636E\u4FDD\u7559\u65F6\u95F4\uFF08\u5206\u949F\uFF09
monitor.retention-minutes=30

process.filter.keywords=java,jdk,jar,jetbrains,IntelliJ,eclipse,intellij,org.netbeans,gradle,maven,jre,jps,jcmd,jconsole,visualvm,jstatd,junit,ApacheJMeter,Application,Bootstrap

# 过滤：类型|包名
## 数据库
filter.mysql=mysql|mysql.*,jpa.*
filter.mongodb=mongodb|mongodb.*,mongo.*
filter.jpa=jap|jpa.*,PagingAndSortingRepository.*,JpaSpecificationExecutor.*

## java
filter.java=java|com.*,java.*
