# NoSQL
com.mongodb.client.*
com.mongodb.client.internal.*
com.mongodb.internal.operation.*
com.mongodb.internal.connection.*
com.mongodb.reactivestreams.client.*
org.apache.hadoop.hbase.client.*
org.apache.hadoop.hbase.ipc.*
org.apache.hadoop.hbase.shaded.*
org.apache.hadoop.ipc.*
com.datastax.oss.driver.api.*
com.datastax.driver.core.*
redis.clients.jedis.*
io.lettuce.core.*
org.elasticsearch.client.*