# common
jdk.*
sun.*
com.sun.*
org.slf4j.*
ch.qos.logback.*
org.apache.logging.*
org.apache.commons.logging.*

org.springframework.*
org.hibernate.*
org.mybatis.*
jakarta.persistence.*
javax.persistence.*