# HTTP 客户端
org.apache.http.*
org.apache.hc.client5.*
org.apache.hc.core5.*
okhttp3.*
okhttp.*
okio.*
jdk.internal.net.http.*

# HTTP 服务器 / 容器
org.apache.coyote.*
org.apache.tomcat.util.net.*
org.apache.tomcat.*
org.eclipse.jetty.*
io.undertow.*
io.netty.*
reactor.netty.*