# ORM / JPA / 数据访问框架
org.springframework.jdbc.core.*
org.mybatis.spring.SqlSessionTemplate.*
org.apache.ibatis.executor.*
org.apache.ibatis.session.*
org.apache.ibatis.mapping.*
org.hibernate.*
jakarta.persistence.*
javax.persistence.*
org.eclipse.persistence.*
org.apache.openjpa.*
org.jooq.*
spring.data.*