# 连接池
com.zaxxer.hikari.*
org.apache.commons.dbcp2.*
org.apache.commons.dbcp.*
com.mchange.v2.c3p0.*
org.apache.tomcat.jdbc.pool.*
com.jolbox.bonecp.*
org.vibur.dbcp.*
io.agroal.*
bitronix.tm.resource.jdbc.*
com.atomikos.jdbc.*
oracle.ucp.jdbc.*
org.jboss.jca.adapters.jdbc.*
com.sun.gjc.spi.*